name: Deploy Site

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Initialize submodules
        run: |
          git submodule update --init --recursive

      # 安装Hugo 
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # 构建Hugo site
      - name: Build
        run: |
          hugo -D
      
      # 推送构建文件夹到另一个分支，例如 gh-pages 分支等
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./public

      - name: Notice
        run: |
          RESPONSE=$(curl -s "https://api.day.app/AgXLBLDNFVfDsNHYHtfAk4/blog%20deploy%20success")
          echo "${RESPONSE}"