name: Deploy Site

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      
      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Check submodules status
        run: |
          git submodule foreach 'git fetch origin'
          git submodule foreach 'git checkout $(git describe --tags)'

      # 安装Hugo 
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.82.0'

          
      # 构建Hugo site
      - name: Build
        run: |
          hugo
      
      # 推送构建文件夹到另一个分支，例如 gh-pages 分支等
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./public