name: Deploy Site

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize submodules
        run: |
          cd themes\Dolt
          git submodule update --init --recursive

      - uses: actions/checkout@v3

      # 安装Hugo 
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # 构建Hugo site
      - name: Build
        run: |
          hugo -D
      
      # 推送构建文件夹到另一个分支，例如 gh-pages 分支等
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./public