name: Deploy

on:
  push:
    branches:
      - main # 主分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build and Deploy
      env:
        DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      run: |
        HUGO_ENV=production hugo --minify && \
        cd public && \
        touch .nojekyll && \
        git init && \
        git config user.name "${{ github.actor }}" && \
        git config user.email "${{ github.actor }}@users.noreply.github.com" && \
        git add . && \
        git commit -m "Deploy to gh-pages" && \
        git branch -M gh-pages && \
        git remote add origin https://github.com/${{ github.repository }}.git && \
        git push -u origin gh-pages --force